In [18]:
import pandas as pd
from pathlib import Path
import numpy as np

In [19]:
#import citibike csv files
Q1_2024_csv = Path("Resources/JC-202401-citibike-tripdata.csv")
Q2_2024_csv = Path("Resources/JC-202404-citibike-tripdata.csv")
Q3_2024_csv = Path("Resources/JC-202407-citibike-tripdata.csv")
Q4_2024_csv = Path("Resources/JC-202410-citibike-tripdata.csv")

#Read in CSV files and store in Pandas Dataframe
Q1_data = pd.read_csv(Q1_2024_csv)
Q2_data = pd.read_csv(Q2_2024_csv)
Q3_data = pd.read_csv(Q3_2024_csv)
Q4_data = pd.read_csv(Q4_2024_csv)

Q1_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member

In [20]:
#merge the 4 csv files (ignore_index=True resets the indexes so they are continous)
merged_df = pd.concat([Q1_data, Q2_data, Q3_data, Q4_data],ignore_index=True)

merged_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
360522,4FBD994F1648B362,electric_bike,2024-10-20 09:59:13.554,2024-10-20 10:08:13.706,Hoboken Ave at Monmouth St,JC105,River St & 1 St,HB609,40.735208,-74.046964,40.737215,-74.028865,casual
360523,204041F23ECD28F1,electric_bike,2024-10-02 18:02:16.294,2024-10-02 18:09:23.766,Hoboken Ave at Monmouth St,JC105,River St & 1 St,HB609,40.735208,-74.046964,40.737215,-74.028865,member
360524,49D3FDDA6932091C,classic_bike,2024-10-12 14:37:23.192,2024-10-12 14:45:56.088,Hoboken Ave at Monmouth St,JC105,River St & 1 St,HB609,40.735208,-74.046964,40.737215,-74.028865,member
360525,DABDE1AAF41AFACB,electric_bike,2024-10-20 13:31:30.895,2024-10-20 13:41:10.722,Hoboken Ave at Monmouth St,JC105,River St & 1 St,HB609,40.735208,-74.046964,40.737215,-74.028865,member
360526,144E2FB38A17608C,electric_bike,2024-10-01 10:42:19.480,2024-10-01 10:58:21.839,Hoboken Ave at Monmouth St,JC105,River St & 1 St,HB609,40.735208,-74.046964,40.737215,-74.028865,member

In [21]:
#check data types for calculations
merged_df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [22]:
#convert started_at and ended_at to datetime objects (had to look up format='mixed' to fix the error from fractional seconds in the dataset). I used this over errors="coerce" because I didn't want it set to NaT ("Not a Time")
merged_df['started_at'] = pd.to_datetime(merged_df['started_at'], format='mixed')
merged_df['ended_at'] = pd.to_datetime(merged_df['ended_at'], format='mixed')
merged_df.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [ ]:
#Calculate Trip duration 
merged_df['trip_duration'] = (merged_df['ended_at'] - merged_df['started_at'])

#used np.ceil to round up to nearest whole number for ease of calculating. The decimal it was producing wasn't in seconds
merged_df['trip_duration'] = np.ceil(merged_df['trip_duration'].dt.total_seconds() / 60) 

#convert to an integer from a float to remove the decimal 
merged_df['trip_duration']= merged_df['trip_duration'].astype(int)
merged_df['trip_duration'].head()

0    15
1     4
2     4
3     4
4     5
Name: trip_duration, dtype: int64

In [24]:
#check how many missing values in each column (count of missing values)
merged_df.isnull().sum()

ride_id                  0
rideable_type            0
started_at               0
ended_at                 0
start_station_name      28
start_station_id        28
end_station_name      1033
end_station_id        1141
start_lat                0
start_lng                0
end_lat                123
end_lng                123
member_casual            0
trip_duration            0
dtype: int64

In [25]:
#remove all rows with missing data and make a copy to avoid error below
merged_df_cleaned = merged_df.dropna().copy()


#check rows after cleaning
merged_df_cleaned.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
trip_duration         0
dtype: int64

In [26]:
# Checking for duplicates
print(merged_df_cleaned.duplicated().sum())

0

In [27]:
# Checking for outliers 
merged_df_cleaned['trip_duration'].describe()

count    359365.000000
mean         10.160831
std          23.301915
min           0.000000
25%           5.000000
50%           7.000000
75%          10.000000
max        1493.000000
Name: trip_duration, dtype: float64

In [ ]:
# Checking if I need to normalize these columns (the answer is no)
print(merged_df_cleaned['rideable_type'].unique())
print(merged_df_cleaned['member_casual'].unique())

['electric_bike' 'classic_bike']
['member' 'casual']

In [29]:
# Add additional fields for Tableau
merged_df_cleaned['start_hour'] = merged_df_cleaned['started_at'].dt.hour
merged_df_cleaned['day_of_week'] = merged_df_cleaned['started_at'].dt.day_name()
merged_df_cleaned.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration,start_hour,day_of_week
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member,15,15,Monday
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member,4,15,Saturday
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,4,13,Friday
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,4,7,Tuesday
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member,5,16,Monday

In [30]:
# Export to csv file
merged_df_cleaned.to_csv('citibike_2024_4Q.csv', index=False)